### ISSUE TITLE
GET bucket resources change index

### ISSUE THREAD

**Issue by chloegugli** [ow2-proactive/catalog#160]
When doing a GET /catalog/buckets/calendars/resources?kind=calendar , the response is not always the same. The objects in the list aren't ordered the same way even if the list contains the same objects. 
I put 2 responses of this request, the 2nd was executed 20 seconds after the first one. You can see that 'every_monday' is line 137 for the 1st request and then line 98 for the 2nd. 
This results in weird behavior in the portal because we don't re-order them. If you select a calendar and the calendar list refreshes, another calendar might be selected instead if the index isn't the same.

**Comment by chloegugli** [comment]
[Response1.txt](https://github.com/ow2-proactive/catalog/files/2718420/Response1.txt)
[Response2.txt](https://github.com/ow2-proactive/catalog/files/2718421/Response2.txt)

**Comment by chloegugli** [comment]
Fix PR in job planner portal : https://bitbucket.org/activeeon/job-planner-portal/pull-requests/165/sorting-calendars-by-name/diff
Issue : https://bitbucket.org/activeeon/job-planner-portal/issues/8/bad-display-when-clicking-on-calendar-in

**Comment by ShatalovYaroslav** [comment]
Closed by https://github.com/ow2-proactive/catalog/pull/165
