### ISSUE TITLE
Session id not required for getting bucket metadata

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#162]
Step to reproduce:
Ensure that the catalog is secured
Send a request against http://localhost:8080/catalog/swagger-ui.html#!/bucket-controller/getMetadataUsingGET with a bad sessionId and an existing bucket.
It return 200 OK instead of 401Unauthorized.

**Comment by fviale** [comment]
@MaelAudren this is normal in catalog non-secure mode

**Comment by MaelAudren** [comment]
This is normal with the default bucket. Indeed a default bucket is public and does not require session id to get the information.
