### ISSUE TITLE
Inconsistent default selection of catalog objects

### ISSUE THREAD

**Issue by mboussaa** [ow2-proactive/catalog#185]
By going through the catalog portal, the default selected catalog object is not the same on the dev environment (trydev) as the one on a local environment.
For examples, It selects "Key_value" object from "basic-examples" bucket on dev however it selects "remote_visualization" by default when accessing catalog portal locally.

I notice that this is applicable to other buckets, not only "basic-examples".

Moreover, the default selection should not use the first element in the displayed list ti be selected? For example, "Native_task" for "basic examples". Why should I scroll down to check out the selected catalog object? 

This should be standardized.

**Comment by medou-boushab** [comment]
https://trello.com/c/aIvSfo1A/4691-inconsistent-default-selection-of-catalog-objects

**Comment by mboussaa** [comment]
@medou-boushab the issue is still present in try

**Comment by medou-boushab** [comment]
Yes I saw it today! It seems that I didn't cherry pick.
