### ISSUE TITLE
Cannot get the raw object with some private content type in swagger

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#41]
With the swagger interface :
Upload it with the content-type "myApp" on /catalog/swagger-ui.html#!/catalog-object-controller/createUsingPOST_1 
=> the object is well uploaded
Get the raw object on /catalog/swagger-ui.html#!/catalog-object-controller/getRawUsingGET
=> it fails 

It seems that it fail only through the swagger interface. 
If the content type is "application/myApp", it works.

**Comment by ShatalovYaroslav** [comment]
According to discussion in card: 
https://trello.com/c/g0Qh92SR/2423-generic-catalog-remove-the-mediatype-check

Just to summarize the possible solutions for content-type:
1) leave as it is now: not adding custom content type to header, close issue
2) add custom content type: avoid creation of MediaType java object and validation
3) try to create MediaType from content-type, if exception, then put in header binary type: application/octet-stream
The choice of the solution depends if we want to allow user to get his own content-type or not.

Final decision: Let's leave it as it is now. Thanks
