### ISSUE TITLE
Generic information name and project_name duplications  

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#63]
The following test has be done through the catalog swagger-ui.
When submitting a workflow the several generic informations are added. Among them, the generic informations name and project_name are added.
After getting the workflow and resubmitting it, the generic informations are added once again. As a consequence, when an user get the workflow, it has two times the generic informations name and project-name instead of once.

**Comment by tobwiens** [comment]
This is solved by #64
