### ISSUE TITLE
Replacement of Generic Information Destroys Formatting

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/catalog#65]
Submitting a workflow with kind="workflow" parses the workflow, removes the Generic Information inside the workflow xml and adds new Generic Information. 

That process has several drawbacks:
- Destroys formatting
- Creates issue with line endings

**Comment by tobwiens** [comment]
Possible solution: 
- Add Geneneric Infromation without formatting or line endings: 
- Prettify the xml output: https://stackoverflow.com/questions/25864316/pretty-print-xml-in-java-8/33541820#33541820

**Comment by ShatalovYaroslav** [comment]
Fixed by PR: #101
