### ISSUE TITLE
Get metadata and delete request fails with object name containing the character "."

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#72]
Create an object named "test.1" in bucket 1000
=> 200 OK
GET  /catalog/buckets/1000/resources/test.1
=> 404 Not Found
DELETE  /catalog/buckets/1000/resources/test.1
=> 404 Not Found
GET  /catalog/buckets/1000/resources/test.1
=> 200 OK with test.1 content

**Comment by ShatalovYaroslav** [comment]
Fixed in https://github.com/ow2-proactive/catalog/pull/93,
Because the name should be: "The bucketName can be between 3 and 63 characters long, and can contain only lower-case characters, numbers, and dashes."
