### ISSUE TITLE
commitTime parameter doesn't match with the response commit_time but with commit_time_raw

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#96]
The parameter name is commit name however when we get the workflow metadata, the required value is named commit_name_raw. commit_name also exist however it is not working as an entry parameter.

**Comment by ShatalovYaroslav** [comment]
@MaelAudren The bug that you are describing here is related to commitTime and not to commitName. Right?

**Comment by MaelAudren** [comment]
@ShatalovYaroslav Indeed the issue concerns the variables commit_time_raw and commit_time. I'll fix the issue title.
